import type { RoleDefinition } from '@/entities/job';

export const roleDefinitions: RoleDefinition[] = [
  {
    id: 'founder',
    name: '창업 개발견',
    lane: 'core',
    summary: '초기 코드를 책임지고 회사를 시작합니다.',
    productionBase: 4.1,
    qualityBase: 1.3,
    focusUse: 1.15,
    teamBuffBase: 0.04,
  },
  {
    id: 'designer',
    name: '디자인 견',
    lane: 'product',
    summary: '화면과 감성을 책임집니다.',
    productionBase: 2.6,
    qualityBase: 1.15,
    focusUse: 0.72,
    teamBuffBase: 0.03,
  },
  {
    id: 'pm',
    name: 'PM 견',
    lane: 'product',
    summary: '우선순위를 조율하고 속도를 끌어올립니다.',
    productionBase: 2.1,
    qualityBase: 0.95,
    focusUse: 0.65,
    teamBuffBase: 0.07,
  },
  {
    id: 'architect',
    name: '아키텍트 견',
    lane: 'platform',
    summary: '장기 생산성과 구조 안정성을 끌어올립니다.',
    productionBase: 2.8,
    qualityBase: 1.4,
    focusUse: 0.82,
    teamBuffBase: 0.08,
  },
  {
    id: 'qa',
    name: 'QA 견',
    lane: 'release',
    summary: '배포 직전 사고를 줄여줍니다.',
    productionBase: 1.9,
    qualityBase: 1.75,
    focusUse: 0.62,
    teamBuffBase: 0.03,
  },
];
